### ISSUE TITLE
Icons don’t match the UI of the app

### ISSUE THREAD

**Issue by dannymout** [systers/FirstAide-iOS#16]
I've noticed that the icons on the "Circle of Trust" screen don't match the overall UI of the applications. The icons have gradients, something that is not used throughout the application that has a flat UI. Also, they are quite blurry/pixelated when I was testing.

**Comment by dannymout** [comment]
I made icons that look more modern. I have committed them to #18

**Comment by sandarumk** [comment]
Hi @dannymout You don't have to fix this. Because we have a separate task to design icons for all the three Android, Web and iOS versions. Because all three should follow a common look and feel. When fixing issues in Github, please communicate with the mentors so that any unnecessary work won't be done. Thank you very much for reporting the task.
