### ISSUE TITLE
Blue links on the "Get Help Now" page aren't very visible on the green background.

### ISSUE THREAD

**Issue by dannymout** [systers/FirstAide-iOS#17]
The blue links on the "Get Help Now" page aren't very visible on the green background. They need to be changed to a colour more visible on the BG.

**Comment by dannymout** [comment]
I've made pull request #18 that fixes this.

**Comment by sandarumk** [comment]
Hi @dannymout In #14 we have suggested you to create a general issue covering the whole app. Since  you have reported the issue only for a certain section, can you go through the app and find out all the locations where the issue persists? 
I even suggested this in the last issue as well. Before you fix an issue and send a PR please contact/ communicate with the mentor on validating the issue and how to proceed. In that case you will be able to avoid extra work.  
For us to accept the Code In task (Fix a reported bug) we need all the locations of the blue links to be fixed. We sent you back the task instance with more work needed, so you can continue fixing all the locations. As a starting step, you can list down all the pages where this blue links are present. We will go through the list and add if any more is missed.

**Comment by dannymout** [comment]
@sandarumk The only screen with this problem is the Get Help Now screen. That's why I made an issue for this specific screen. I've made a new pull request that solves this exact problem: #19.

**Comment by dannymout** [comment]
@sandarumk @chamika The only screen with this problem is the Get Help Now screen. That's why I made an issue for this specific screen. I've made a new pull request that solves this exact problem: #19.

**Comment by sandarumk** [comment]
@dannymout Sorry about that. I forgot that we haven't implemented "Policies and Glossary" in the iOS version. We will review your pull request and let you know.

**Comment by dannymout** [comment]
@sandarumk I will look into writing code that'll automatically set the `tintColor` to yellow for all UITextViews, so when the Policies and Glossary is added I won't need to go back in and change each TextView individually.

**Comment by chamika** [comment]
https://github.com/systers/FirstAide-iOS/pull/19
