### ISSUE TITLE
Personal Security Strategies Broken Segue

### ISSUE THREAD

**Issue by YashBit** [systers/FirstAide-iOS#31]
Then b
![unknown](https://cloud.githubusercontent.com/assets/20094677/21081123/2eced774-bfe6-11e6-9506-3b07bfaf122c.png)
utton Personal Security Strategy seems to have no segue , or the screen itself is missing.

**Comment by chamika** [comment]
Let me remind you what we instructed earlier. Before posting any issue, go through the issue list in both open and closed areas. This will remove having duplicate issues.
Refer: https://github.com/systers/FirstAide-iOS/issues/21

I'm closing this issue because it is invalid for the same reason as #21
