### ISSUE TITLE
UI Improvement: contacts for circle of trust

### ISSUE THREAD

**Issue by erikatan** [systers/FirstAide-iOS#41]
I made a google doc describing the issue. Here is the link: https://docs.google.com/document/d/1ngnuyt1f-MZMR2XC8z82kdpI_ERLKFQ_aotRAXTfPr8/edit?usp=sharing

**Comment by chamika** [comment]
@erikatan Thank you for your suggestions.

Please find the feedback for the suggestions
Current Behavior
1. In real device clicking Help Me Button will navigate to message app. There user can see all the numbers. This cannot be viewed from simulator. 

Suggestions
1. Edit Screen : There can be numbers which are not picked from the contacts. In this scenario we don't have a contact name to show. Therefore it would be great if we can add name + number in the same text field. Ex: John (012345562) for contacts and 0123213213 for non-contacts.
Then we don't have to add another text field for names.

2. Circle of Trust: Good suggestion.

3. Information : Again good suggestion

Can you describe the above suggestions (1, 2, 3) and open separate issues for them. 
1 - Open a new issue since it is related to Edit Screen.
2,3 - Open a single issue and describe two suggestions in the same issue.

**Comment by erikatan** [comment]
@chamika I have created the new issues. Thanks!

**Comment by chamika** [comment]
Thank you for reporting issues
