### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by ronakdev** [systers/FirstAide-iOS#44]
# Help Page
After using the app for 2 days (getting acquiainted with it and such) I realized that the app lacks on key feature: A help page. While the help page should not show automatically, there should definietly be a help page within the app that shows the main features of the app are. 

For example, when you download the Google Drive app for the first time, it shows you a basic overview of all main functions of the app.

A mockup of how this might be done

![tutorial screen](https://cloud.githubusercontent.com/assets/9388431/21437869/208eaec0-c83b-11e6-8812-4c89ed23cf33.png)

# Home Screen Link
In addition, while users can get to the home screen by launching the app or by hitting the back button, this is really inefficient. 

Current Menu

![home screen](https://cloud.githubusercontent.com/assets/9388431/21437871/20914180-c83b-11e6-9dbc-0d9a7cbc81ee.png)

We should implement a link available from the hamburger menu (perhaps an additional link called "Home" or making the "peace corps" logo a link that takes the user back to the homescreen. This will help users understand where to go and reduce confusion within the app.

Mockup of new menu

![new menu](https://cloud.githubusercontent.com/assets/9388431/21437870/208f10e0-c83b-11e6-9f5b-f2919f182063.png)

**Comment by ronakdev** [comment]
To clarify, this was done as part of GCI 2016

**Comment by sandarumk** [comment]
@ronakdev Thank you very much for your valuable ideas. One thing to note is that these come under functionality improvements rather than the user interface improvements.  The reason we have not included a link to the home page is because we can access all the items in the home screen with the hamburger menu option. This is there for users to directly access the pages they want without going back to the home screen.
Now about your first suggestion. We have not included a help page is that the functionality of the app is fairly straight forward. This app is not designed for the use of the general public. It is for the Peace Corps volunteers who has an idea of what to expect. More over since all the information are categorized in the home page another help page is not necessary.

**Comment by ronakdev** [comment]
For number one, the addition of a home menu item is quite simple to add, and will be quite useful — even to experienced users. It won't be a deterrent and will certainly not go under appreciated. I acknowledge that the users of the app will not be ordinary people, but including a tutorial screen will still help users familiarise themselves with the app.

**Comment by sandarumk** [comment]
A tutorial screen is useful if the users has something to do in the app because they have to figure out how to do it. We already have an unpublished task to add (design and implement) a tutorial similar to Android app to the circle of trust functionality (Which will be published soon for GCI). But for the whole app it is unnecessary because they have to just go and read the information. The only section of the app where the users has to do something is in the Circle of Trust. That is why we are limiting the tutorial only to the circle of trust.

**Comment by chamika** [comment]
Since the improvements are not acceptable, closing the issue
