### ISSUE TITLE
Suggestion: Disable Swipeback to reveal menu; make swipeback go back

### ISSUE THREAD

**Issue by ronakdev** [systers/FirstAide-iOS#45]
In the app, if you swipe back, (meaning you drag your finger from the left side of the screen to the right, it currently brings up the hamburger menu. This is impractical because users of the app may find themselves simply trying to get back to the page they were just in.

This concept of swiping back is very common within apps, for example in the native Safari app users swipe back to go back one page.

Part of GCI

**Comment by chamika** [comment]
@ronakdev These are two concepts and we have to select one over the other.
In Safari there is no hamburger menu and going back from swipe is straight forward.
But FirstAide has a hamburger menu which enables the user to navigate to almost any screen in the app. So instead of going back, he/she can go to any screen with a swipe and a tap. Also, there are two buttons for going back and forward if necessary. 
In my opinion, activating side menu is more user friendlier than just going back. 
Also take a look at the [Gmail app](https://itunes.apple.com/us/app/gmail-email-by-google-secure/id422689480?mt=8) which has hamburger menu and it activates the menu, not the back. 

If you have any ideas let us know.
