### ISSUE TITLE
Policies and Glossary not accessible

### ISSUE THREAD

**Issue by tiferrei** [systers/FirstAide-iOS#51]
Hello there,
I have noticed that even though there are buttons and events for the Policies and Glossary" menu tab and button, these do not actually link to any view controller or information.

These should not be part of the `dataSource` until they are usable. I understand this is in development stage, however, this is also present in the master branch, which based on your master - develop model, I assume to be your production branch, and this would cause a lot of confusion to the users. I suggest that the code is commented out, removed or simply moved to a new feature branch to organise the repo.

I have included a [video](https://github.com/systers/FirstAide-iOS/files/699816/Bug.zip) demonstrating the effects of this bug.

Hope I have been of help,
Tiago

**Comment by jacqueline8711** [comment]
Hi, I'm currently developing these screens and I will be able to finish them in about two days. I think it can stay the way it is until then.

**Comment by tiferrei** [comment]
Personally I don't believe it to be the best of the ideas, floating code is never good, you should either get the menu and main view code on your fork and work on it, or move it to a feature branch, but that's more up to the admins to decide.

**Comment by chamika** [comment]
@tiferrei This is not in production level. We maintain a stable code in the master branch. From time to time, we merge develop branch code to the master branch. Since this is not in live, having that kind of behavior is acceptable. Also, this was developed under GSoC 2016, it was a requirement to have all the UI components similar to Android. That is why these elements are placed in such manner. 

Since this is invalid. I'm closing the issue.
