### ISSUE TITLE
Implement Sexual Assault Awareness Screen(s)

### ISSUE THREAD

**Issue by chamika** [systers/FirstAide-iOS#7]
App should support all the features which are currently available in FirstAide-Android App. 
Therefore we need to develop Sexual Assault Awareness Screens and menu navigation.

Steps
1. Go through the Android application screens before start implementing it. [Source](https://github.com/systers/FirstAide-Android)

2. Submit a design/mockup screens which covers Android App features. But screens should adhere the iOS design guidelines

3. Once the design/mockup screens are finalized, we can start the development

The content for these screens are available in this [document](https://drive.google.com/file/d/0B8cm8EBZg0GaQy1CUkRUOXhWZUE/view)

The screen should navigate from main screen button and the slide menu.
![sexual_assault](https://cloud.githubusercontent.com/assets/754909/20606488/4515f974-b297-11e6-8a5d-a5007526a0ff.png)

**Comment by YashBit** [comment]
Hi , please can this task be assigned to me ?

**Comment by chamika** [comment]
Since @YashBit is working on another issue, this is open to anyone

**Comment by YashBit** [comment]
Hi , I have solved the issue . But I cannot find a task own cgi task site which relates to the problem of solving an issue . What should I do ?

**Comment by chamika** [comment]
@YashBit , I think you selected the https://github.com/systers/FirstAide-iOS/issues/8 issue. Please use that issue page for communication.

**Comment by jacqueline8711** [comment]
These are the designs / mockups I created for the GCI task. They all have the same content as the Android screens except for the "Sexual Harassment" screen. There I made one out of the two Android screens because they both had the same heading. 

<img width="375" alt="awareness_menu" src="https://cloud.githubusercontent.com/assets/16260112/21080121/5222916e-bfa7-11e6-8b18-e8b55337add3.png">
<img width="375" alt="awareness_wasitassault" src="https://cloud.githubusercontent.com/assets/16260112/21080164/65014a72-bfa8-11e6-90c0-702358c769fc.png">
<img width="374" alt="awareness_sexualassault" src="https://cloud.githubusercontent.com/assets/16260112/21080165/67bfbd98-bfa8-11e6-8b07-12a639ed3e7a.png">
<img width="375" alt="awareness_commonquestions" src="https://cloud.githubusercontent.com/assets/16260112/21080172/b130938a-bfa8-11e6-8b1c-dab2f51d7687.png">
<img width="376" alt="awareness_impact" src="https://cloud.githubusercontent.com/assets/16260112/21080167/726b4f64-bfa8-11e6-9706-8ba6cde33858.png">
<img width="375" alt="awareness_harassment" src="https://cloud.githubusercontent.com/assets/16260112/21080168/7d7cf6b4-bfa8-11e6-9987-7c9ae138169a.png">
<img width="377" alt="awareness_helpothers" src="https://cloud.githubusercontent.com/assets/16260112/21080169/802beaa0-bfa8-11e6-992e-57775ef1e1c5.png">

Are those designs okay? If yes, I'd like to implement them.

**Comment by chamika** [comment]
Screens look good. Please find the following modification.
Sexual Harassment section should be separated similar to Android version.

Add a separate button like "Learn more about sexual harassment" and navigate to another screen.
The new screen will have the content of "What is sexual harassment?"

The content can be found from [https://drive.google.com/file/d/0B8cm8EBZg0GaQy1CUkRUOXhWZUE/view](https://drive.google.com/file/d/0B8cm8EBZg0GaQy1CUkRUOXhWZUE/view)

No need to add the image which is in the content. But add these actions as bullet points in the text.
If you have any concerns let us know.

Make the changes and comment here with the mock screens of sexual harassment.

**Comment by jacqueline8711** [comment]
These are the separated "Sexual Harassment" screens:
<img width="374" alt="awareness_harassment_1" src="https://cloud.githubusercontent.com/assets/16260112/21081005/62c80506-bfbd-11e6-9c68-18556ffa18f1.png">
<img width="372" alt="awareness_harassment_2" src="https://cloud.githubusercontent.com/assets/16260112/21080970/aa95ae0c-bfbc-11e6-8e51-ac25c5cdb106.png">

**Comment by chamika** [comment]
@jacqueline8711  The designs are fine. Good Work!!!

**Comment by chamika** [comment]
If you are interested you can work on developing these sections

**Comment by jacqueline8711** [comment]
Yes, thank you, I'll start implementing them now. I have already claimed the gci task.
